### ISSUE TITLE
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !

### ISSUE THREAD

**Issue by ghost** [KimiNewt/pyshark#116]
Windows 10 , Python 3.4.3 

Script:

```
import pyshark
cap = pyshark.FileCapture("d:\\2.pcapng")
cap
print(cap[0])
```

[2.zip](https://github.com/KimiNewt/pyshark/files/90116/2.zip)

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.2\helpers\pydev\pydev_run_in_console.py", line 69, in <module>
    globals = run_file(file, None, None)
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.2\helpers\pydev\pydev_run_in_console.py", line 29, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files (x86)\JetBrains\PyCharm 5.0.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc) 
  File "D:/PDCA/Network/pyshark2.py", line 4, in <module>
    print(cap[0])
  File "C:\Python34\lib\site-packages\pyshark\capture\file_capture.py", line 63, in __getitem__
    next(self)
  File "C:\Python34\lib\site-packages\pyshark\capture\file_capture.py", line 53, in __next__
    packet = self._packet_generator.send(None)
  File "C:\Python34\lib\site-packages\pyshark\capture\capture.py", line 173, in _packets_from_tshark_sync
    self._get_packet_from_stream(tshark_process.stdout, data, psml_structure=psml_structure))
  File "C:\Python34\lib\site-packages\trollius\base_events.py", line 300, in run_until_complete
    return future.result()
  File "C:\Python34\lib\site-packages\trollius\futures.py", line 287, in result
    raise self._exception
  File "C:\Python34\lib\site-packages\trollius\tasks.py", line 255, in _step
    result = next(coro)
  File "C:\Python34\lib\site-packages\pyshark\capture\capture.py", line 281, in _get_packet_from_stream
    packet = packet_from_xml_packet(packet, psml_structure=psml_structure)
  File "C:\Python34\lib\site-packages\pyshark\tshark\tshark_xml.py", line 27, in packet_from_xml_packet
    xml_pkt = lxml.objectify.fromstring(xml_pkt, parser)
  File "src\lxml\lxml.objectify.pyx", line 1801, in lxml.objectify.fromstring (src\lxml\lxml.objectify.c:25156)
  File "src\lxml\lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src\lxml\lxml.etree.c:77937)
  File "src\lxml\parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:116734)
  File "src\lxml\parser.pxi", line 1707, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:115384)
  File "src\lxml\parser.pxi", line 1079, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:109783)
  File "src\lxml\parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:103644)
  File "src\lxml\parser.pxi", line 683, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:105298)
  File "src\lxml\parser.pxi", line 613, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:104207)
lxml.etree.XMLSyntaxError: Input is not proper UTF-8, indicate encoding !
Bytes: 0xD6 0xD0 0xB9 0xFA, line 6, column 75
```

**Comment by elektm93** [comment]
I have the same problem on Win7 using WinPython-32bit-2.7.10.3.

see also [here](https://ask.wireshark.org/questions/51447/tshark-crashes-due-to-no-proper-utf8-encoding)

**Comment by elektm93** [comment]
It is now solved for me! See [this link](http://stackoverflow.com/questions/36421788/windows-pyshark-xmlsyntaxerror/36639841#36639841)

I had to add following line between line 26 + 27 in src\pyshark\tshark\tshark_xml.py:

> xml_pkt = xml_pkt.decode('latin-1')

`python setup.py install` and done

**Comment by outdoxl** [comment]
refer @elektm93 's solution, i solved my problem with following code : 
`xml_pkt = unicode(xml_pkt, errors='ignore')`
