### ISSUE TITLE
can not use pyshark module on windows 10, python2.7

### ISSUE THREAD

**Issue by whxloveyrh** [KimiNewt/pyshark#140]
>>> import pyshark

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pyshark
  File "D:\Python27\lib\site-packages\pyshark-0.2.7-py2.7.egg\pyshark\__init__.py", line 1, in <module>
    from pyshark.capture.live_capture import LiveCapture
  File "D:\Python27\lib\site-packages\pyshark-0.2.7-py2.7.egg\pyshark\capture\live_capture.py", line 1, in <module>
    from pyshark.capture.capture import Capture
  File "D:\Python27\lib\site-packages\pyshark-0.2.7-py2.7.egg\pyshark\capture\capture.py", line 4, in <module>
    from pyshark.tshark.tshark import get_tshark_path
  File "D:\Python27\lib\site-packages\pyshark-0.2.7-py2.7.egg\pyshark\tshark\tshark.py", line 8, in <module>
    from pyshark.config import get_config
  File "D:\Python27\lib\site-packages\pyshark-0.2.7-py2.7.egg\pyshark\config.py", line 2, in <module>
    import py
ImportError: No module named py
>>> import py

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import py
ImportError: No module named py
>>>

**Comment by KimiNewt** [comment]
If you install pyshark via pypi or the setup.py, it should have installed all requirements, including py.

You can just run "pip install py" to fix this particular thing but I imagine you lack other requirements so just run pyshark's setup again.
