### ISSUE TITLE
pyshark crashes loop_reading

### ISSUE THREAD

**Issue by ghost** [KimiNewt/pyshark#193]
- Looks like it comes from trollius package?

`Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...op_reading()]>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...op_reading()]>)>
Traceback (most recent call last):
  File "C:\Python\Python35\lib\site-packages\trollius\events.py", line 151, in _run
    self._callback(*self._args)
  File "C:\Python\Python35\lib\site-packages\trollius\proactor_events.py", line 168, in _loop_reading
    data = fut.result()  # deliver data later in "finally" clause
  File "C:\Python\Python35\lib\site-packages\trollius\futures.py", line 276, in result
    raise InvalidStateError('Result is not ready.')
trollius.futures.InvalidStateError: Result is not ready.
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...ess (resolve'>)`

- So what i am doing:
`capture     = pyshark.LiveCapture(interface='XXXX')`
`for packet in capture.sniff_continuously():`
`      #some packet processing`
- When: after some while, like maybe 1h maybe 20min
- Probable cause: i don't know, maybe it is because of heavy packet processing?

**Comment by teddyarmagedon** [comment]
Hey, does anybody have a clue?

**Comment by haotian-001** [comment]
same problem...

**Comment by Gurgel69** [comment]
Same here. But on a file that have a couple of seconds from the Wifi.

import pyshark

cf = pyshark.FileCapture(input_file="e.pcapng")

paket = cf[0]
print(paket)

Packet (Length: 694)
Layer ETH:
        Destination: 01:00:5e:7f:ff:fa
        Address: 01:00:5e:7f:ff:fa
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...1 .... .... .... .... = IG bit: Group address (multicast/broadcast)
        Source: 54:04:a6:bf:cc:79
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
        Type: IPv4 (0x0800)
        Address: 54:04:a6:bf:cc:79
Layer IP:
        0100 .... = Version: 4
        .... 0101 = Header Length: 20 bytes (5)
        Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
        Total Length: 680
        Identification: 0xfbaa (64426)
        Flags: 0x0000
        0... .... .... .... = Reserved bit: Not set
        .0.. .... .... .... = Don't fragment: Not set
        ..0. .... .... .... = More fragments: Not set
        Fragment offset: 0
        Time to live: 1
        Protocol: UDP (17)
        Header checksum: 0xa503 [validation disabled]
        Header checksum status: Unverified
        Source: 192.168.101.244
        Destination: 239.255.255.250
Layer UDP:
        Source Port: 64922
        Destination Port: 3702
        Length: 660
        Checksum: 0x3627 [unverified]
        Checksum Status: Unverified
        Stream index: 0
        Timestamps
        Time since first frame: 0.000000000 seconds
        Time since previous frame: 0.000000000 seconds
DATA
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...: Locally ad'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...: Locally ad'>)>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 299, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 441, in recv
    self._register_with_iocp(conn)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 714, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] Felaktig parameter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 309, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 131, in _fatal_error
    self._force_close(exc)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 134, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 769, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 441, in recv
    self._register_with_iocp(conn)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 714, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] Felaktig parameter
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001C245C85280>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_subprocess.py", line 126, in __del__
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed

**Comment by shiruiyan** [comment]
Seeing same issue here. Is this issue fixed?

.......
Layer UDP:
        Source Port: 8801
        Destination Port: 55639
        Length: 402
        Checksum: 0xdb69 [unverified]
        Checksum Status: Unverified
        Stream index: 0
        Timestamps
        Time since first frame: 0.000000000 seconds
        Time since previous frame: 0.000000000 seconds
        UDP payload (394 bytes)
DATA
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF... showname="T'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF... showname="T'>)>
Traceback (most recent call last):
  File "D:\Tools\anaconda3\lib\asyncio\proactor_events.py", line 299, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "D:\Tools\anaconda3\lib\asyncio\windows_events.py", line 445, in recv
    self._register_with_iocp(conn)
  File "D:\Tools\anaconda3\lib\asyncio\windows_events.py", line 718, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Tools\anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Tools\anaconda3\lib\asyncio\proactor_events.py", line 309, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "D:\Tools\anaconda3\lib\asyncio\proactor_events.py", line 131, in _fatal_error
    self._force_close(exc)
  File "D:\Tools\anaconda3\lib\asyncio\proactor_events.py", line 134, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "D:\Tools\anaconda3\lib\asyncio\proactor_events.py", line 777, in _loop_self_reading
    f = self._proactor.recv(self._ssock, 4096)
  File "D:\Tools\anaconda3\lib\asyncio\windows_events.py", line 445, in recv
    self._register_with_iocp(conn)
  File "D:\Tools\anaconda3\lib\asyncio\windows_events.py", line 718, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] 参数错误。
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000021C50F10C10>
Traceback (most recent call last):
  File "D:\Tools\anaconda3\lib\asyncio\base_subprocess.py", line 126, in __del__
    self.close()
  File "D:\Tools\anaconda3\lib\asyncio\base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "D:\Tools\anaconda3\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Tools\anaconda3\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "D:\Tools\anaconda3\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by xiaoaiwhc** [comment]
```
cap = pyshark.FileCapture(input_file="e.pcapng")
cap.close()
```

Using `cap.close()` can bypass this issue, maybe this is an issue about Python3.7.
[pyshark Cannot access data regarding packet](https://stackoverflow.com/questions/60151460/pyshark-cannot-access-data-regarding-packet/70480445#70480445)
