### ISSUE TITLE
pyshark crashes under both mac and linux

### ISSUE THREAD

**Issue by wumin1** [KimiNewt/pyshark#205]
pyshark crashes while sniff continuously, the error message is following:

[2017-07-13 03:40:44.028327] DEBUG: LiveRingCapture: %s subprocess created
[2017-07-13 03:40:44.028805] DEBUG: LiveRingCapture: Creating TShark subprocess with parameters: /usr/local/bin/tshark -l -n -T pdml -r - -b filesize:1024 -b files:1 -w /tmp/pyshark.pcap -P
[2017-07-13 03:40:44.031049] DEBUG: LiveRingCapture: %s subprocess created
Capturing on 'Ethernet'
File: -
tshark: Multiple capture files requested, but a capture isn't being done.
[2017-07-13 03:40:44.150440] DEBUG: LiveRingCapture: EOF reached (sync)
Traceback (most recent call last):
  File "capture_tst.py", line 10, in <module>
    for packet in capture.sniff_continuously(packet_count=100):
  File "/Volumes/PLHome/tmp/pyshark-master/src/pyshark/capture/capture.py", line 225, in _packets_from_tshark_sync
    self.eventloop.run_until_complete(self._cleanup_subprocess(tshark_process))
  File "/Library/Python/2.7/site-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/Library/Python/2.7/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception pyshark.capture.capture.TSharkCrashException: TSharkCrashException(u'TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.',) in <bound method LiveRingCapture.__del__ of <LiveRingCapture (0 packets)>> ignored

**Comment by wumin1** [comment]
Never mind. My mistake -- problem solved after I change 'LiveRingCapture' into 'LiveCapture'.
