### ISSUE TITLE
TShark crashes when parsing pcap for SSL features

### ISSUE THREAD

**Issue by Srivathsan-Srinivas** [KimiNewt/pyshark#207]
When I run in iPython mode (2.7.x):

```
In [7]: cap = pyshark.FileCapture('../input/pcaps/89a0f20b73492ffbcb1242437131ba76b6b0fa150782a5149b26da5d55f24dd1.pcap', display_filter='ssl')

In [8]: for pkt in cap:
   ...:     print pkt
```

I am able to see the pkts and their layers. But, when I create a Python program and define a function to do the same, TShark crashes:

```
(venv) $ python feature-extraction.py /Users/test/signatures/input/pcaps/89a0f20b73492ffbcb1242437131ba76b6b0fa150782a5149b26da5d55f24dd1.pcap

Traceback (most recent call last):
  File "feature-extraction.py", line 292, in <module>
    main()
  File "feature-extraction.py", line 286, in main
    ssl_features = get_ssl_features(pcap_file)
  File "feature-extraction.py", line 97, in get_ssl_features
    for pkt in cap:
  File "/Users/test/venv/lib/python2.7/site-packages/pyshark/capture/capture.py", line 225, in _packets_from_tshark_sync
    self.eventloop.run_until_complete(self._cleanup_subprocess(tshark_process))
  File "/Users/test/venv/lib/python2.7/site-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/Users/test/venv/lib/python2.7/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 2). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
(venv) $
```

Not sure what is happening. Any thoughts why parsing the same pcap in one way is working well (iPython mode) and in another way (Regular Python code) is not working?

**Comment by Srivathsan-Srinivas** [comment]
must use 'ssl' in display filter instead of 'secure sockets layer'. That was the root cause.
