### ISSUE TITLE
TShark seems to have crashed

### ISSUE THREAD

**Issue by elenabdc** [KimiNewt/pyshark#225]
I have seen the same error in some earlier version, I'm using pyshark v 0.3.7.9 on Debian 9

The error is the next one:

> [2017-10-01 16:28:06.536929] DEBUG: LiveCapture: %s subprocess created
[2017-10-01 16:28:06.537982] DEBUG: LiveCapture: Creating TShark subprocess with parameters: /usr/bin/tshark -l -n -T pdml -w home/user/test.pcap -r -
[2017-10-01 16:28:06.542313] DEBUG: LiveCapture: %s subprocess created
[2017-10-01 16:28:06.543002] DEBUG: LiveCapture: Starting to go through packets
Running as user "root" and group "root". This could be dangerous.
tshark: Lua: Error during loading:
 [string "/usr/share/wireshark/init.lua"]:44: dofile has been disabled due to running Wireshark as superuser. See https://wiki.wireshark.org/CaptureSetup/CapturePrivileges for help in running Wireshark as an unprivileged user.
Capturing on 'wlan2mon'
File: -
tshark: The file "home/ki-wips/test.pcap" could not be created: No existe el fichero o el directorio.
[2017-10-01 16:28:08.026662] DEBUG: LiveCapture: EOF reached
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 124, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 243, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/local/lib/python3.5/dist-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/dist-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/trollius/tasks.py", line 255, in _step
    result = next(coro)
  File "/usr/local/lib/python3.5/dist-packages/trollius/tasks.py", line 424, in wait_for
    raise Return(fut.result())
  File "/usr/local/lib/python3.5/dist-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 261, in packets_from_tshark
    yield From(self._close_async())
  File "/usr/local/lib/python3.5/dist-packages/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 412, in _close_async
    yield From(self._cleanup_subprocess(process))
  File "/usr/local/lib/python3.5/dist-packages/trollius/tasks.py", line 255, in _step
    result = next(coro)
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 404, in _cleanup_subprocess
    raise TSharkCrashException('TShark seems to have crashed (retcode: %d). Try rerunning in debug mode [ capture_obj.set_d
ebug() ] or try updating tshark.' % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 2). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
exit()
Exception ignored in: <bound method Capture.__del__ of <LiveCapture (0 packets)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 417, in __del__
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 407, in close
  File "/usr/local/lib/python3.5/dist-packages/trollius/base_events.py", line 300, in run_until_complete
  File "/usr/local/lib/python3.5/dist-packages/trollius/futures.py", line 287, in result
  File "/usr/local/lib/python3.5/dist-packages/trollius/tasks.py", line 251, in _step
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 412, in _close_async
  File "/usr/local/lib/python3.5/dist-packages/trollius/tasks.py", line 255, in _step
  File "/usr/local/lib/python3.5/dist-packages/pyshark/capture/capture.py", line 404, in _cleanup_subprocess
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 2). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

Edit:
I have tested it and the problem appears on defining an output_file param.

Is there any possible way to fix it?

Thank you.

**Comment by SerhiyRomanov** [comment]
The same problem( Please help!

**Comment by jcao1022** [comment]
We met the same error, is there a plan to fix it?

**Comment by TobiasFrahm** [comment]
Hello,

I ran into the same problem when defining the output_file param. But it works if you create the targeted file before. 
That may helps. 

Greets.
