### ISSUE TITLE
Tshark Crash Report Error 

### ISSUE THREAD

**Issue by adityasriv22** [KimiNewt/pyshark#232]
# capture.sniff(timeout=50)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/capture.py", line 124, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/capture.py", line 243, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/local/lib/python2.7/dist-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/trollius/futures.py", line 287, in result
    raise self._exception
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

I am getting this error even when I tried all the above mentioned solution
please resolve it or provide solution

**Comment by tricia0127** [comment]
excuse me, do you have solved it? I am meeting this error, too.

**Comment by tricia0127** [comment]
excuse me, have you solved it? I am meeting this error, too.

**Comment by valenting** [comment]
This bug is really annoying.

I got around it by doing this:

```python
def print_callback(pkt):
    print 'Just arrived:', pkt

def start():
  print "starting capture"

  try:
    capture.apply_on_packets(print_callback, timeout=10000)
  except:
    start()

start()
```

**Comment by cavusogluerdem** [comment]
Have you solved this ? I have the same error too.

**Comment by edcSam** [comment]
has this bug been fixed?

**Comment by KimiNewt** [comment]
I'm not sure what this bug is supposed to be? Timeouts work fine for me. That particular exception just means that tshark crashed and doesn't say anything.

Please run `capture.set_debug()` before running the `sniff()` function and post the results here.

**Comment by arurangg** [comment]
[2018-07-14 11:21:02.111366] DEBUG: LiveCapture: Creating Dumpcap subprocess with parameters: /usr/bin/dumpcap -q -P -i enp7s0 -w -
[2018-07-14 11:21:02.113572] DEBUG: LiveCapture: %s subprocess created
[2018-07-14 11:21:02.114085] DEBUG: LiveCapture: Creating TShark subprocess with parameters: /usr/bin/tshark -l -n -T pdml -r -
[2018-07-14 11:21:02.117845] DEBUG: LiveCapture: %s subprocess created
[2018-07-14 11:21:02.118331] DEBUG: LiveCapture: Starting to go through packets
Capturing on 'enp7s0'
File: -
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pyshark/capture/capture.py", line 132, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/pyshark/capture/capture.py", line 247, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

**Comment by KimiNewt** [comment]
There was an issue with the exceptions. Try it with the latest version from master.

**Comment by kakirastern** [comment]
I am seeing a similar error while running `pyshark` today...

So I ran the following code: 
```
import pyshark
capture = pyshark.LiveCapture()
capture.set_debug()
capture.sniff(timeout=60)
```
And I got the following error(s) with traceback:
```
[2019-07-16 14:47:11.793979] DEBUG: LiveCapture: Creating Dumpcap subprocess with parameters: /usr/local/bin/dumpcap -q -i 1 -i 2 -i 3 -i 4 -i 5 -i 6 -i 7 -i 8 -i 9 -i 10 -i 11 -i 12 -i 13 -i 14 -w -
[2019-07-16 14:47:11.797830] DEBUG: LiveCapture: Dumpcap subprocess created
[2019-07-16 14:47:11.798527] DEBUG: LiveCapture: Creating TShark subprocess with parameters: /usr/local/bin/tshark -l -n -T pdml -r -
[2019-07-16 14:47:11.798610] DEBUG: LiveCapture: Executable: /usr/local/bin/tshark
[2019-07-16 14:47:11.802333] DEBUG: LiveCapture: TShark subprocess created
[2019-07-16 14:47:11.802588] DEBUG: LiveCapture: Starting to go through packets
dumpcap: There is no interface with that adapter index

Task exception was never retrieved
future: <Task finished coro=<Capture.packets_from_tshark() done, defined at /anaconda3/envs/pysyft/lib/python3.7/site-packages/pyshark/capture/capture.py:270> exception=TSharkCrashException('TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.')>
Traceback (most recent call last):
  File "/anaconda3/envs/pysyft/lib/python3.7/site-packages/pyshark/capture/capture.py", line 279, in packets_from_tshark
    await self._go_through_packets_from_fd(tshark_process.stdout, packet_callback, packet_count=packet_count)
  File "/anaconda3/envs/pysyft/lib/python3.7/site-packages/pyshark/capture/capture.py", line 297, in _go_through_packets_from_fd
    psml_structure=psml_struct)
  File "/anaconda3/envs/pysyft/lib/python3.7/site-packages/pyshark/capture/capture.py", line 357, in _get_packet_from_stream
    new_data = await stream.read(self.DEFAULT_BATCH_SIZE)
  File "/anaconda3/envs/pysyft/lib/python3.7/asyncio/streams.py", line 640, in read
    await self._wait_for_data('read')
  File "/anaconda3/envs/pysyft/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/pysyft/lib/python3.7/site-packages/pyshark/capture/capture.py", line 284, in packets_from_tshark
    await self._close_async()
  File "/anaconda3/envs/pysyft/lib/python3.7/site-packages/pyshark/capture/capture.py", line 432, in _close_async
    await self._cleanup_subprocess(process)
  File "/anaconda3/envs/pysyft/lib/python3.7/site-packages/pyshark/capture/capture.py", line 425, in _cleanup_subprocess
    % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
```
What can I do to fix these? Any suggestions?

**Comment by kakirastern** [comment]
Sorry, problem solved... Turns out I needed in manually input the `interface` as I cannot set it to `None` and expect pyshark to automatically detect the first available interface. Anyway, is this a bug in itself? Just curious to know.

**Comment by li2haipeng** [comment]
2020-10-07 00:04:03,041 - LiveCapture - DEBUG - Creating Dumpcap subprocess with parameters: /usr/bin/dumpcap -q -f ip host 192.168.200.39 || tcp -i enp0s31f6 -w -
2020-10-07 00:04:03,045 - LiveCapture - DEBUG - Dumpcap subprocess created
2020-10-07 00:04:03,045 - LiveCapture - DEBUG - Creating TShark subprocess with parameters: /usr/bin/tshark -l -n -T pdml -w /home/erc/Desktop/nvsk/papers/javascript/pcap/website_pcapFiles_100/test_google/test_1_Chrome.pcap -r -
2020-10-07 00:04:03,045 - LiveCapture - DEBUG - Executable: /usr/bin/tshark
2020-10-07 00:04:03,047 - LiveCapture - DEBUG - TShark subprocess created
2020-10-07 00:04:03,048 - LiveCapture - DEBUG - Starting to go through packets
Capturing on 'enp0s31f6'
File: -
Traceback (most recent call last):
  File "loadDrivertest2a.py", line 42, in <module>
    web_crawler('test_google', 'https://google.com/', '192.168.200.39', 30, 29)
  File "loadDrivertest2a.py", line 33, in web_crawler
    capture.sniff(timeout = 30)
  File "/home/erc/.local/lib/python3.8/site-packages/pyshark/capture/capture.py", line 137, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "/home/erc/.local/lib/python3.8/site-packages/pyshark/capture/capture.py", line 277, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
