### ISSUE TITLE
Windows 10 tshark crash (raw packet data)

### ISSUE THREAD

**Issue by AMNeves** [KimiNewt/pyshark#248]
When running:

```
import pyshark
capture = pyshark.LiveCapture(interface="Local Area Connection")
capture.set_debug()
capture.sniff(timeout=10)
capture
```

i seem to have a problem, i cant sniff any packets and tshark crashes with output:

```
PS C:\Users\amnev\Documents\anomaly shark> python .\packets.py
[2018-02-15 05:46:03.259102] DEBUG: LiveCapture: %s subprocess created
[2018-02-15 05:46:03.260070] DEBUG: LiveCapture: Creating TShark subprocess with parameter
 -r -
[2018-02-15 05:46:03.274069] DEBUG: LiveCapture: %s subprocess created
[2018-02-15 05:46:03.275069] DEBUG: LiveCapture: Starting to go through packets
tshark: You can't write both raw packet data and dissected packets to the standard output.
```

seems to be a problem with the output of tshark any ideas how to solve this i cant run the simple capture code

**UPDATE**: i can sniff with tshark just not with pyshark

**Comment by wubucheng** [comment]
Do you solve this problem? I meet the same problem.

**Comment by Inspirateur** [comment]
same :(

**Comment by KimiNewt** [comment]
Does this happen on the new / python3 version as well?

**Comment by eric-guanwy** [comment]
same :(

python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshark
>>> capture = pyshark.LiveCapture(interface="-i 6")
>>> capture.set_debug()
>>> capture.sniff(timeout=10)
[2018-06-28 05:52:32.614029] DEBUG: LiveCapture: %s subprocess created
[2018-06-28 05:52:32.615035] DEBUG: LiveCapture: Creating TShark subprocess with parameters: C:\Program Files\Wireshark\tshark.exe -l -n -T pdml -r -
[2018-06-28 05:52:32.621534] DEBUG: LiveCapture: %s subprocess created
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyshark-0.4.0-py3.6.egg\pyshark\capture\capture.py", line 132, in load_packets

    self.apply_on_packets(keep_packet, timeout=timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyshark-0.4.0-py3.6.egg\pyshark\capture\capture.py", line 247, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyshark-0.4.0-py3.6.egg\pyshark\capture\capture.py", line 256, in packets_from_tshark
    tshark_process = await self._get_tshark_process(packet_count=packet_count)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyshark-0.4.0-py3.6.egg\pyshark\capture\live_capture.py", line 92, in _get_tshark_process
    raise tshark
TypeError: exceptions must derive from BaseException
>>> tshark: You can't write both raw packet data and dissected packets to the standard output.

**Comment by KimiNewt** [comment]
Solved in last commit.

**Comment by hanisyuhada** [comment]
what is the solution?

**Comment by hanisyuhada** [comment]
how to solve the problem?

**Comment by username30** [comment]
Using pyshark 0.4.2.3 and still confirm this behavior.

**Comment by KimiNewt** [comment]
@username30 which Wireshark/tshark version are using?
I'm not seeing this error. We can remove the `-P` option like @PrettyUp but I want to make sure it's related to the problem.

**Comment by username30** [comment]
TShark (Wireshark) 3.0.2 (v3.0.2-0-g621ed351d5c9)
Wireshark reports the same version at About dialog.

Mine Python is 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) and I run this whole setup under Windows 7.

**Comment by username30** [comment]
UPD: and yes, removing `-P` as suggested above helps.

**Comment by KimiNewt** [comment]
I'm not sure why it fails when using the `pcap` format (it doesn't on my machine, but that's what the -P flag does), but at any rate tshark can get `pcapng` from version 2.5 so I'll change it so if the version is newer than that it'll use it.
