### ISSUE TITLE
Adding decryption_key to pyshark.FileCapture fails to parse file

### ISSUE THREAD

**Issue by nightrune** [KimiNewt/pyshark#249]
I have a 3.3 gig wireshark capture that I used an Airpcap interface to capture with. If I parse the file without decryption then it seems to parse fine but adding a key returns zero packets.

**Comment by KimiNewt** [comment]
Did you select the appropriate decryption method? Can you post the code (without the key..)?

**Comment by Casual-Alchemist** [comment]
Hi,
I am using tshark version 3.2.2 and pyshark version 0.4.2.9 in ubuntu 16.04.6
playing with decryption_key, encryption_type arguments in livecapture using python code
```
import pyshark
capture = pyshark.LiveCapture(interface='wlp2s0', output_file='packets.pcap', decryption_key='password', encryption_type='wpa-psk')
capture.sniff(timeout=10)
print(capture)`
```
for that i am getting following error
```
Traceback (most recent call last):
  File "livecaptur.py", line 3, in <module>
    capture.sniff(timeout=10)
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 137, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 277, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 293, in packets_from_tshark
    await self.close_async()
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 441, in close_async
    await self._cleanup_subprocess(process)
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 434, in _cleanup_subprocess
    % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception ignored in: <bound method Capture.__del__ of <LiveCapture (0 packets)>>
Traceback (most recent call last):
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 446, in __del__
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 437, in close
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 441, in close_async
  File "/home/ram/.local/lib/python3.5/site-packages/pyshark/capture/capture.py", line 434, in _cleanup_subprocess
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/base_events.py", line 431, in __del__
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 58, in close
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 139, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```
I am just trying the the basic example given in GitHub, am I missing anything here,
This code is not waiting for capture.sniff timeout period, when i run it, instantly showing this error.
Any suggestions would be help full,
Thanks in advance.
