### ISSUE TITLE
When reading Multiple files through pyshark it is throwing error

### ISSUE THREAD

**Issue by surya1104** [KimiNewt/pyshark#304]
Exception ignored in: <bound method Capture.__del__ of <FileCapture .\PCAP_spilt_files\exportpcap_00000_20180109182629.pcap>>
Traceback (most recent call last):
  File "C:\Users\navuru\AppData\Local\Programs\Python\Python36\lib\site-packages\pyshark-0.4.1-py3.6.egg\pyshark\capture\capture.py", line 412, in __del__
    self.close()
  File "C:\Users\navuru\AppData\Local\Programs\Python\Python36\lib\site-packages\pyshark-0.4.1-py3.6.egg\pyshark\capture\capture.py", line 403, in close
    self.eventloop.run_until_complete(self._close_async())
  File "C:\Users\navuru\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\navuru\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 411, in run_forever
    'Cannot run the event loop while another loop is running')
RuntimeError: Cannot run the event loop while another loop is running

`for filename in self.spilt_file_name:
                                self.cap = pyshark.FileCapture('.\\PCAP_spilt_files\\' + filename)
                                for idp ,pkt in enumerate(self.cap):
                                                        print (pkt.show())`

**Comment by DingerZhang** [comment]
Hi,

I met the same problem when I used python==3.7.0, pyshark==0.4.1 and tornado==5.1. 
I read some issues and solutions in this list and then created a new environment with python==3.5.2, pyshark==0.3.7.11 and tornado==4.5.3. It works well now.

Thanks,

**Comment by solidossnakos** [comment]
I was having random errors related to cap = pyshark.FileCapture(file).
What worked for me is using:
cap.close() 
PS: I'm using cap = pyshark.FileCapture(file) in multiple threads(not main)

**Comment by KimiNewt** [comment]
What OS are you using?
