### ISSUE TITLE
Exeption while live capturing in a thread

### ISSUE THREAD

**Issue by ignagnu** [KimiNewt/pyshark#308]
Python 2.7.15rc1
ubuntu 18.04 4.15.0-39-generic
Wireshark 2.6.4

I have this simple code:
```
import pyshark
from collections import deque
import threading
import sys


class Sniffer(threading.Thread):
    def __init__(self):
        threading.Thread.__init__(self)
        self.coda = deque()
        self.cap = pyshark.LiveCapture(interface='loopback', only_summaries=1)

    def listen_for_packet(self, pkt):
        self.coda.append(pkt)
        print(pkt)
        if "icmp" in str(pkt):
            print("ping")
        return False

    def run(self):
        #self.cap.sniff(packet_count=100, timeout=10)
        self.cap.sniff_continuously()
        self.cap.apply_on_packets(self.listen_for_packet)

if __name__ == "__main__":
    monitor = Sniffer()
    monitor.start()

    while True:
        data = sys.stdin.readline()
        if "exit" in data:
            break
    print("exit")

```
When i try to run get this error.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/ignazio/PycharmProjects/gsmtester/modulo_sniffer.py", line 27, in run
    self.cap.apply_on_packets(self.listen_for_packet)
  File "/home/ignazio/PycharmProjects/gsmtester/venv/local/lib/python2.7/site-packages/pyshark/capture/capture.py", line 256, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "/home/ignazio/PycharmProjects/gsmtester/venv/local/lib/python2.7/site-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/home/ignazio/PycharmProjects/gsmtester/venv/local/lib/python2.7/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
RuntimeError: There is no current event loop in thread 'Thread-1'
```

Notice that if i remove the thread part, it works like a sharm. 
Ps. on python 3 works, but i need python 2 for this project

**Comment by KimiNewt** [comment]
Move the creation of the cap to the `run()` function. The initialization creates the eventloop in the wrong thread because `__init__`  runs in the original thread.

In general I would recommend using `asyncio` for parallelization with psyhark
