### ISSUE TITLE
Is it common for it to Pyshark to crash after 9 packets?

### ISSUE THREAD

**Issue by Josh-Work** [KimiNewt/pyshark#332]
Exception ignored in: <function Capture.__del__ at 0x11506DB0>
Traceback (most recent call last):
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyshark\capture\capture.py", line 412, in __del__
    self.close()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyshark\capture\capture.py", line 403, in close
    self.eventloop.run_until_complete(self._close_async())
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyshark\capture\capture.py", line 407, in _close_async
    await self._cleanup_subprocess(process)
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyshark\capture\capture.py", line 400, in _cleanup_subprocess
    % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

**Comment by KimiNewt** [comment]
Please attach the code you were running (or explain it), and use cap.set_debug() beforehand to catch any tshark errors.
