### ISSUE TITLE
Pyshark crashing when breaking for loop

### ISSUE THREAD

**Issue by gaardiolor** [KimiNewt/pyshark#339]
Windows 10
Tshark 3.0.2
Pyhon 3.7.1
Pyshark 0.4.2.3

Pyshark throws exception when breaking out of for-loop. 

This works:
```
import pyshark


def main():
    file = 'C:\\_Data\\Pcap\\error.pcap'
    cap = pyshark.FileCapture(file)
    cap.set_debug()
    for counter, pkt in enumerate(cap):
        pass


if __name__ == "__main__":
    main()
```

This doesn't:
```
import pyshark


def main():
    file = 'C:\\_Data\\Pcap\\error.pcap'
    cap = pyshark.FileCapture(file)
    cap.set_debug()
    for counter, pkt in enumerate(cap):
        if counter == 10:
            break


if __name__ == "__main__":
    main()

```
Error:
```
C:\Users\gaardiolor\PycharmProjects\pcap_tools\venv\Scripts\python.exe C:/Users/gaardiolor/PycharmProjects/pcap_tools/test.py
[2019-05-27 17:59:41.999429] DEBUG: FileCapture: Creating TShark subprocess with parameters: C:/Program Files/Wireshark/tshark.exe -l -n -T pdml -r C:\_Data\Pcap\error.pcap
[2019-05-27 17:59:41.999429] DEBUG: FileCapture: Executable: C:/Program Files/Wireshark/tshark.exe
[2019-05-27 17:59:42.006407] DEBUG: FileCapture: TShark subprocess created
Exception ignored in: <function Capture.__del__ at 0x000001F502498268>
Traceback (most recent call last):
  File "C:\Users\gaardiolor\PycharmProjects\pcap_tools\venv\lib\site-packages\pyshark\capture\capture.py", line 434, in __del__
    self.close()
  File "C:\Users\gaardiolor\PycharmProjects\pcap_tools\venv\lib\site-packages\pyshark\capture\capture.py", line 425, in close
    self.eventloop.run_until_complete(self._close_async())
  File "C:\Users\gaardiolor\Anaconda3\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "C:\Users\gaardiolor\PycharmProjects\pcap_tools\venv\lib\site-packages\pyshark\capture\capture.py", line 429, in _close_async
    await self._cleanup_subprocess(process)
  File "C:\Users\gaardiolor\PycharmProjects\pcap_tools\venv\lib\site-packages\pyshark\capture\capture.py", line 422, in _cleanup_subprocess
    % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

Process finished with exit code 0
```

Workaround: If I call `cap.close()` before `break` there's no error. But should that really be needed ?

**Comment by markgras** [comment]
I believe that this is the same issue as #395. You should definitely close your FileCapture, but depending on how you do so TShark may crash.

This fails:
```
import pyshark


def main():
    file = 'C:\\_Data\\Pcap\\error.pcap'
    cap = pyshark.FileCapture(file)
    cap.set_debug()
    try:
        for counter, pkt in enumerate(cap):
            if counter == 10:
                break
    finally:
        cap.close()


if __name__ == "__main__":
    main()
```

And this fails:
```
import pyshark


def main():
    file = 'C:\\_Data\\Pcap\\error.pcap'
    with pyshark.FileCapture(file) as cap:
        cap.set_debug()
        for counter, pkt in enumerate(cap):
            if counter == 10:
                break


if __name__ == "__main__":
    main()
```

But this does not:
```
import pyshark


def main():
    file = 'C:\\_Data\\Pcap\\error.pcap'
    cap = pyshark.FileCapture(file)
    cap.set_debug()
    for counter, pkt in enumerate(cap):
        if counter == 10:
            cap.close()
            break


if __name__ == "__main__":
    main()
```

The last code snippet doesn't follow good coding practices, however, because the `cap.close()` line is not always reached. If `counter` never reaches `10` for whatever reason (the pcap is too small, an error occurs, etc.) then the FileCapture won't be properly closed.

**Comment by ricsi046** [comment]
I had to iterate through packets multiple times with using breaks. Breaking a 'for packet in cap' loop seems to be bugged, so I ended up using a while loop with packet index instead of using pyshark generator and the errors were gone.
