### ISSUE TITLE
Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by new-gen23** [KimiNewt/pyshark#348]
I installed pyshark using: 

> pip3 install pyshark

"locate" confirms it is installen in 

> /usr/local/lib/python3.7/dist-packages/pyshark/

Now when I run "python3.7" and enter "import pyshark", I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/pyshark/__init__.py", line 13, in <module>
    from pyshark.capture.live_capture import LiveCapture
  File "/usr/local/lib/python3.7/dist-packages/pyshark/capture/live_capture.py", line 5, in <module>
    from pyshark.capture.capture import Capture
  File "/usr/local/lib/python3.7/dist-packages/pyshark/capture/capture.py", line 8, in <module>
    import logbook
  File "/usr/local/lib/python3.7/dist-packages/logbook/__init__.py", line 14, in <module>
    from .base import (
  File "/usr/local/lib/python3.7/dist-packages/logbook/base.py", line 22, in <module>
    from logbook.helpers import (PY2, cached_property, integer_types, iteritems,
  File "/usr/local/lib/python3.7/dist-packages/logbook/helpers.py", line 60, in <module>
    from http import client as http_client
ImportError: bad magic number in 'http': b'\x03\xf3\r\n'
```

I am using: 
Linux sw-c-051 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux

**Comment by new-gen23** [comment]
More Info:
```
pip show pyshark
Name: pyshark
Version: 0.4.2.3
Summary: Python wrapper for tshark, allowing python packet parsing using wireshark dissectors
Home-page: https://github.com/KimiNewt/pyshark
```

**Comment by new-gen23** [comment]
Building from source creates other errors:
```
byte-compiling build/bdist.linux-x86_64/egg/pyshark/capture/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyshark/capture/remote_capture.py to remote_capture.pyc
byte-compiling build/bdist.linux-x86_64/egg/pyshark/capture/live_capture.py to live_capture.pyc
  File "build/bdist.linux-x86_64/egg/pyshark/capture/live_capture.py", line 90
    async def _get_tshark_process(self, packet_count=None, stdin=None):
            ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/pyshark/capture/inmem_capture.py to inmem_capture.pyc
  File "build/bdist.linux-x86_64/egg/pyshark/capture/inmem_capture.py", line 65
    async def _get_tshark_process(self, packet_count=None):
            ^
SyntaxError: invalid syntax
```

**Comment by new-gen23** [comment]
Ok, problem has gone. What I did to remove the half installed source version:

`pip2 uninstall pyshark`

Then:

`pip3 install pyshark`

Now, "import pyshark works". Must have been my messed up system. Sorry.
