### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by Yilong94** [KimiNewt/pyshark#366]
> Exception ignored in: <bound method Capture.__del__ of <FileCapture sample-pcap/tls/ari.nus.edu.sg_2018-12-24_14-30-02.pcap>>
Traceback (most recent call last):
  File "/home/foo/bar/baz/venv/lib/python3.6/site-packages/pyshark/capture/capture.py", line 446, in __del__
    self.close()
  File "/home/foo/bar/baz/venv/lib/python3.6/site-packages/pyshark/capture/capture.py", line 437, in close
    self.eventloop.run_until_complete(self.close_async())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

Python version: 3.6.8
Pyshark version: 0.4.2.9

I encountered a RuntimeError whenever I execute pyshark.FileCapture on more than 1 pcap file. Happens quite randomly with no clear pattern. The RuntimeError is  ignored and the code will run to completion. However, I am just curious as to why this might happen.

Digging deeper, it seems like pyshark is trying to close the filecapture object, but ended up calling run_forever in asyncio, which seems rather counterintuitive and resulted in asyncio raising the warning that the thread is still running. Perhaps I am not understanding how asyncio interacts with pyshark? Thanks

Code to run:
`sample_filecapture = pyshark.FileCapture(sample, use_json=True, debug=True)`

**Comment by Yilong94** [comment]
Solved. Closing the FileCapture would remove the error. 

Example:
`
sample_filecapture = pyshark.FileCapture(sample, use_json=True, debug=True)
sample_filecapture.close()
`

Seems like having multiple FileCapture would create multiple eventloops
