### ISSUE TITLE
Crash with asyncio on python 3.5

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [KimiNewt/pyshark#388]
Installed pyshark with pip in my userspace and tried

    import pyshark
    var = pyshark.FileCapture('myfile.pcapng')

pyshark returned

    Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
    Traceback (most recent call last):
      File "/usr/lib/python3.5/asyncio/base_events.py", line 510, in __del__
      File "/usr/lib/python3.5/asyncio/unix_events.py", line 65, in close
      File "/usr/lib/python3.5/asyncio/unix_events.py", line 146, in remove_signal_handler
      File "/usr/lib/python3.5/signal.py", line 47, in signal
    TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

**Comment by GrehXscape** [comment]
Have you fixed it? Running into the same issue here, and I can't find any answer to it.
