### ISSUE TITLE
UnicodeDecodeError when reading a packet

### ISSUE THREAD

**Issue by cglewis** [KimiNewt/pyshark#389]
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyshark-0.4.2.9-py3.7.egg/pyshark/capture/capture.py", line 246, in _packets_from_tshark_sync
    got_first_packet=packets_captured > 0))
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/pyshark-0.4.2.9-py3.7.egg/pyshark/capture/capture.py", line 361, in _get_packet_from_stream
    packet = packet_from_json_packet(packet)
  File "/usr/local/lib/python3.7/site-packages/pyshark-0.4.2.9-py3.7.egg/pyshark/tshark/tshark_json.py", line 26, in packet_from_json_packet
    pkt_dict = json.loads(json_pkt.decode('utf-8'), object_pairs_hook=duplicate_object_hook)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x99 in position 20715: invalid start byte
```

**Comment by cglewis** [comment]
So I just build from the latest in master and this problem goes away. Any chance the newer versions could be pushed up to PyPi?

**Comment by cglewis** [comment]
@KimiNewt please can you publish the latest release to PyPi? I can't have this project as a dependency because I have to use git to build the latest release through pip, which PyPi doesn't support, and I can't use the older (latest posted) version on PyPi because of the above error.
