### ISSUE TITLE
Crash when FileCapture closes without running to completion.

### ISSUE THREAD

**Issue by markgras** [KimiNewt/pyshark#395]
## Environment info
- Python 3.7.6 64-Bit
- Pyshark 0.4.2.9
- Windows and Tshark info:
```
H:\>"C:/Program Files/Wireshark/tshark.exe" --version
TShark (Wireshark) 3.2.1 (v3.2.1-0-gbf38a67724d0)

Copyright 1998-2020 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with WinPcap SDK (WpdPack) 4.1.2, with GLib 2.52.3, with zlib
1.2.11, with SMI 0.4.8, with c-ares 1.15.0, with Lua 5.2.4, with GnuTLS 3.6.3
and PKCS #11 support, with Gcrypt 1.8.3, with MIT Kerberos, with MaxMind DB
resolver, with nghttp2 1.39.2, with brotli, with LZ4, with Zstandard, with
Snappy, with libxml2 2.9.9.

Running on 64-bit Windows 10 (1909), build 18363, with Intel(R) Core(TM)
i7-6820HQ CPU @ 2.70GHz (with SSE4.2), with 32588 MB of physical memory, with
locale English_United States.1252, with Npcap version 0.9986, based on libpcap
version 1.9.1, with GnuTLS 3.6.3, with Gcrypt 1.8.3, with brotli 1.0.2, binary
plugins supported (0 loaded).

Built using Microsoft Visual Studio 2019 (VC++ 14.24, build 28315).
```

## Issue
Tshark crashes when the pyshark file capture closes without running to completion. Two flavors of code are shown below.

Flavor 1:
```
import pyshark


def iterate_through_pcap(file_name):
    cap = pyshark.FileCapture(file_name, keep_packets=False)
    cap.set_debug()
    try:
        for i, pkt in enumerate(cap):

            # Parse packet
            pass

            # Yield result
            yield i
    finally:
        cap.close()


if __name__ == '__main__':
    result = iterate_through_pcap('test0.pcapng')
    print(next(result))
```

Traceback 1:
```
C:\Python37\python.exe C:/Users/mgrassi/Desktop/test/pyshark_error.py
2020-02-12 09:53:34,323 - FileCapture - DEBUG - Creating TShark subprocess with parameters: C:/Program Files/Wireshark/tshark.exe -l -n -T pdml -r test0.pcapng
2020-02-12 09:53:34,323 - FileCapture - DEBUG - Executable: C:/Program Files/Wireshark/tshark.exe
2020-02-12 09:53:34,332 - FileCapture - DEBUG - TShark subprocess created
0
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...ip.flags.df"'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...ip.flags.df"'>)>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 254, in _packets_from_tshark_sync
    yield packet
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\proactor_events.py", line 274, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "C:\Python37\lib\asyncio\windows_events.py", line 423, in recv
    self._register_with_iocp(conn)
  File "C:\Python37\lib\asyncio\windows_events.py", line 650, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python37\lib\asyncio\proactor_events.py", line 284, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Python37\lib\asyncio\proactor_events.py", line 110, in _fatal_error
    self._force_close(exc)
  File "C:\Python37\lib\asyncio\proactor_events.py", line 113, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
Exception ignored in: <generator object iterate_through_pcap1 at 0x000001551C9F2EC8>
Traceback (most recent call last):
  File "C:/Users/mgrassi/Desktop/test/pyshark_error.py", line 16, in iterate_through_pcap1
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 437, in close
  File "C:\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 441, in close_async
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 434, in _cleanup_subprocess
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception ignored in: <function Capture.__del__ at 0x000001551CAA6D38>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 446, in __del__
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 437, in close
  File "C:\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 441, in close_async
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 434, in _cleanup_subprocess
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x000001551C8C90D8>
Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\base_subprocess.py", line 127, in __del__
  File "C:\Python37\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Python37\lib\asyncio\proactor_events.py", line 86, in close
  File "C:\Python37\lib\asyncio\base_events.py", line 687, in call_soon
  File "C:\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed

Process finished with exit code 0
```

Flavor 2:
```
import pyshark


def iterate_through_pcap(file_name):
    with pyshark.FileCapture(file_name, keep_packets=False) as cap:
        cap.set_debug()
        for i, pkt in enumerate(cap):

            # Parse packet
            pass

            # Yield result
            yield i


if __name__ == '__main__':
    result = iterate_through_pcap('test0.pcapng')
    print(next(result))
```

Traceback 2:
```
C:\Python37\python.exe C:/Users/mgrassi/Desktop/test/pyshark_error.py
2020-02-12 09:55:05,476 - FileCapture - DEBUG - Creating TShark subprocess with parameters: C:/Program Files/Wireshark/tshark.exe -l -n -T pdml -r test0.pcapng
2020-02-12 09:55:05,476 - FileCapture - DEBUG - Executable: C:/Program Files/Wireshark/tshark.exe
2020-02-12 09:55:05,483 - FileCapture - DEBUG - TShark subprocess created
0
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...ip.flags.df"'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...ip.flags.df"'>)>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 254, in _packets_from_tshark_sync
    yield packet
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\proactor_events.py", line 274, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 32768)
  File "C:\Python37\lib\asyncio\windows_events.py", line 423, in recv
    self._register_with_iocp(conn)
  File "C:\Python37\lib\asyncio\windows_events.py", line 650, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] The parameter is incorrect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Python37\lib\asyncio\proactor_events.py", line 284, in _loop_reading
    self._fatal_error(exc, 'Fatal read error on pipe transport')
  File "C:\Python37\lib\asyncio\proactor_events.py", line 110, in _fatal_error
    self._force_close(exc)
  File "C:\Python37\lib\asyncio\proactor_events.py", line 113, in _force_close
    if self._empty_waiter is not None and not self._empty_waiter.done():
AttributeError: '_ProactorReadPipeTransport' object has no attribute '_empty_waiter'
Exception ignored in: <generator object iterate_through_pcap2 at 0x00000251526A2EC8>
Traceback (most recent call last):
  File "C:/Users/mgrassi/Desktop/test/pyshark_error.py", line 28, in iterate_through_pcap2
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 450, in __exit__
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 437, in close
  File "C:\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 441, in close_async
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 434, in _cleanup_subprocess
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception ignored in: <function Capture.__del__ at 0x0000025152756D38>
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 446, in __del__
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 437, in close
  File "C:\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 441, in close_async
  File "C:\Python37\lib\site-packages\pyshark\capture\capture.py", line 434, in _cleanup_subprocess
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000251525790D8>
Traceback (most recent call last):
  File "C:\Python37\lib\asyncio\base_subprocess.py", line 127, in __del__
  File "C:\Python37\lib\asyncio\base_subprocess.py", line 104, in close
  File "C:\Python37\lib\asyncio\proactor_events.py", line 86, in close
  File "C:\Python37\lib\asyncio\base_events.py", line 687, in call_soon
  File "C:\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
RuntimeError: Event loop is closed

Process finished with exit code 0
```

Both finish without error if `print(next(result))` is changed to `list(result)`, meaning that the file capture is completely parsed.

**Comment by icysea-blog** [comment]
def main(file_name):
    count = 1
    test = pyshark.FileCapture(input_file=file_name, keep_packets=False)
    test.set_debug()
    for pac in test:
        print(pac.layers)
        count += 1

2020-04-28 18:12:41,802 - FileCapture - DEBUG - EOF reached (sync)
Exception ignored in: <function Capture.__del__ at 0x11b21bae8>
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 2). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

So how can I know it reaches the end of the pcap file ?

**Comment by Lukkimon** [comment]
Maybe solution that i found would help #501
