### ISSUE TITLE
"asyncio.exceptions.TimeoutError" How to fix this?

### ISSUE THREAD

**Issue by H1de0nbush** [KimiNewt/pyshark#402]
Hi , I'm using python 3.8 and pyshark 0.4.2.9
Here is my code running on pycharm, Windows 10, it's very simple :
```
import pyshark

def wireshark():
    path = "F:\\Wireshark\\tshark.exe"
    cap = pyshark.LiveCapture(tshark_path=path, interface="Ether 4", output_file="test.pcap")
    cap.sniff(timeout=5)
```
And get these errors:
```
Traceback (most recent call last):
  File "E:/PyProjects/Unname/Test.py", line 19, in <module>
    wireshark()
  File "E:/PyProjects/Unname/Test.py", line 7, in wireshark
    cap.sniff(timeout=1)
  File "E:\PyProjects\Unname\venv\lib\site-packages\pyshark\capture\capture.py", line 137, in load_packets
    self.apply_on_packets(keep_packet, timeout=timeout)
  File "E:\PyProjects\Unname\venv\lib\site-packages\pyshark\capture\capture.py", line 277, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "C:\Users\30447\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\30447\AppData\Local\Programs\Python\Python38\lib\asyncio\tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
And the test.pcap is a blank pcap file.

**Comment by normchri** [comment]
Hey, 
I have the same problem as you mentionned, any fix from your side ? 

Thanks

**Comment by wangzhenshan3** [comment]
If it doesn't affect your needs, you can grab the package through Wireshark first, then save the file and use pyshark.filecapture to operate the package you caught.

I still can't use pyshark.livecapture normally

**Comment by JackyWu0311** [comment]
I had the same problem with python 3.8 and pyshark 0.4.2.9
After I changed to python 2.7 and pyshark 0.3.8 ,this problem was solved.
Hope this can help you.

**Comment by tmntdapp** [comment]
Hey,
I have the same problem as you mentionned, any fix from your side ?

Thanks

**Comment by PaleNeutron** [comment]
Same, platform is macOS 10.15, python3.8.5
