### ISSUE TITLE
TimeoutError (Exception ignored in: <function Capture.__del__ at 0x7765cca4f940>)

### ISSUE THREAD

**Issue by lattice0** [KimiNewt/pyshark#430]
```
cap = pyshark.FileCapture('capture1_bug.pcapng')
print(cap[1]['ip'].dst)
```

I get

```
172.17.0.2
Exception ignored in: <function Capture.__del__ at 0x7765cca4f940>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyshark/capture/capture.py", line 435, in __del__
  File "/usr/local/lib/python3.8/dist-packages/pyshark/capture/capture.py", line 426, in close
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
  File "/usr/local/lib/python3.8/dist-packages/pyshark/capture/capture.py", line 430, in close_async
  File "/usr/local/lib/python3.8/dist-packages/pyshark/capture/capture.py", line 412, in _cleanup_subprocess
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
asyncio.exceptions.TimeoutError: 
```

PS: I had to install my own tshark with `apt-get install -y tshark` because the lib couldn't find tshark even if wireshark was installed. Ubuntu 20 on docker.

Also `print(cap)` gives `<FileCapture capture1_bug.pcapng>`, with no size estimation so I can know how many. Doing `len(cap)` gives `0`.

**Comment by javier-es** [comment]
Please, try closing the capture after being used. This should fix TimeoutError exception.
```
cap = pyshark.FileCapture('capture1_bug.pcapng')
print(cap[1]['ip'].dst)
cap.close()
```
