### ISSUE TITLE
Pyshark runtime error while reading .pcap file

### ISSUE THREAD

**Issue by halarhaleem** [KimiNewt/pyshark#434]
Hi, 
I am using python 3.6.10, pyshark 0.4.2.11 and i am trying to read a .pcap file saved using wireshark but facing the issue.  I have ubuntu 18.04 OS and I used simple three line code as given below. Can some one help out for the below mentioned error.

import pyshark
cap = pyshark.FileCapture('example-01.pcap')
print (cap[0])

Here is the error:

Task exception was never retrieved
future: <Task finished coro=<Capture._get_tshark_process() done, defined at /home/hlr/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyshark/capture/capture.py:375> exception=TSharkNotFoundException("TShark not found. Try adding its location to the configuration file. Searched these paths: ['C:\\\\Program Files\\\\Wireshark\\\\tshark.exe', '/home/hlr/anaconda3/envs/pytorch/bin/tshark', '/home/hlr/anaconda3/condabin/tshark', '/home/hlr/anaconda3/bin/tshark', '/usr/local/sbin/tshark', '/usr/local/bin/tshark', '/usr/sbin/tshark', '/usr/bin/tshark', '/sbin/tshark', '/bin/tshark', '/usr/games/tshark', '/usr/local/games/tshark', '/snap/bin/tshark']",)>
Traceback (most recent call last):
  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyshark/capture/capture.py", line 388, in _get_tshark_process
    self.get_parameters(packet_count=packet_count) + output_parameters
  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyshark/capture/capture.py", line 364, in _get_tshark_path
    return get_process_path(self.tshark_path)
  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyshark/tshark/tshark.py", line 60, in get_process_path
    "Searched these paths: {}".format(possible_paths)
pyshark.tshark.tshark.TSharkNotFoundException: TShark not found. Try adding its location to the configuration file. Searched these paths: ['C:\\Program Files\\Wireshark\\tshark.exe', '/home/hlr/anaconda3/envs/pytorch/bin/tshark', '/home/hlr/anaconda3/condabin/tshark', '/home/hlr/anaconda3/bin/tshark', '/usr/local/sbin/tshark', '/usr/local/bin/tshark', '/usr/sbin/tshark', '/usr/bin/tshark', '/sbin/tshark', '/bin/tshark', '/usr/games/tshark', '/usr/local/games/tshark', '/snap/bin/tshark']
Traceback (most recent call last):

  File "/home/hlr/halar/sample dataset/Python_files/untitled2.py", line 6, in <module>
    print (cap[0])

  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyshark/capture/file_capture.py", line 71, in __getitem__
    self.next()

  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyshark/capture/file_capture.py", line 61, in next
    packet = self._packet_generator.send(None)

  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/site-packages/pyshark/capture/capture.py", line 226, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())

  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/asyncio/base_events.py", line 475, in run_until_complete
    self.run_forever()

  File "/home/hlr/anaconda3/envs/pytorch/lib/python3.6/asyncio/base_events.py", line 429, in run_forever
    raise RuntimeError('This event loop is already running')

RuntimeError: This event loop is already running

**Comment by halarhaleem** [comment]
Hi, 

My issue resolved by following below steps: 

1. pip install nest_asyncio
2. Then adding below TWO lines in main file.
import nest_asyncio
nest_asyncio.apply()

Further details of this solution are available at: https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python

Thanks,
