### ISSUE TITLE
accessing frame information

### ISSUE THREAD

**Issue by lowdef** [KimiNewt/pyshark#45]
I'd like to access  the frame information from the dissected packet. 
In the pdml it is there (allthough not strictly speaking a protocol layer), so why can't I acces it?

```
>>> cap=pyshark.FileCapture(filename)
>>> p=cap[21]
>>> p['frame']._field_names
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/src/pyshark/src/pyshark/packet/packet.py", line 47, in __getitem__
    raise KeyError('Layer does not exist in packet')
>>> p['frame'].frame_number
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/src/pyshark/src/pyshark/packet/packet.py", line 47, in __getitem__
    raise KeyError('Layer does not exist in packet')
KeyError: 'Layer does not exist in packet'
```

I guess it has todo with this fragment from 'tshark_xml.py':

```
def _packet_from_pdml_packet(pdml_packet):
    layers = [Layer(proto) for proto in pdml_packet.proto]
    geninfo, frame, layers = layers[0], layers[1], layers[2:]
    frame.raw_mode = True
    return Packet(layers=layers, length=geninfo.get_field_value('len'), sniff_time=geninfo.get_field_value('timestamp', raw=True),
                  captured_length=geninfo.get_field_value('caplen'), interface_captured=frame.get_field_value('interface_id'))

```

Is there something against 'geninfo' and 'frame' to be also accessible as packet information?

**Comment by openSourceMaker** [comment]
How to get the information that which packet is TCP or UDP?
