### ISSUE TITLE
lxml.etree.XMLSyntaxError

### ISSUE THREAD

**Issue by JamZheng** [KimiNewt/pyshark#450]
I have troubles executing pyShark on Windows. 

 ```
 File "asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "ite-packages\pyshark\capture\capture.py", line 352, in _get_packet_from_stream
    packet = packet_from_xml_packet(packet, psml_structure=psml_structure)
  File "site-packages\pyshark\tshark\tshark_xml.py", line 26, in packet_from_xml_packet
    xml_pkt = lxml.objectify.fromstring(xml_pkt, parser)
  File "src\lxml\objectify.pyx", line 1808, in lxml.objectify.fromstring
  File "src\lxml\etree.pyx", line 3237, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 123
lxml.etree.XMLSyntaxError: invalid character in attribute value, line 123, column 220
Exception ignored in: <function Capture.__del__ at 0x00000290C7CFF1E0>
Traceback (most recent call last):
  File "pyshark\capture\capture.py", line 435, in __del__
  File "pyshark\capture\capture.py", line 426, in close
  File "src\lxml\parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src\lxml\parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src\lxml\parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src\lxml\parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src\lxml\parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src\lxml\parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 123
lxml.etree.XMLSyntaxError: invalid character in attribute value, line 123, column 220
```

And I  try to solve this problem by changing File "pyshark\tshark\tshark_xml.py", line 25, in packet_from_xml_packet
`  parser = lxml.objectify.makeparser(huge_tree=True,recover = True) `
by now it works

**Comment by oneiroi333** [comment]
Same problem here. This error has to be catched and the packet that couldnt be parsed should be skipped so that it is possible to continue analyzing subsequent packets.

**Comment by nishant1994** [comment]
The solution given by @JamZheng is really working. Can you please publish a new release to pip with this fix?
