### ISSUE TITLE
Why can not i get dns query name？

### ISSUE THREAD

**Issue by DD152** [KimiNewt/pyshark#469]
```
import pyshark
c=pyshark.FileCapture(input_file='mshh.pcapng')
```
when i use`print(c[0])` ,it print
 ```
...
Layer DNS:
        ...
        Queries
        Name: www.microsoft.com
        ...
....
```
but when i try  `print(c[0].dns.qry.name)`,it will get blow error
```
Traceback (most recent call last):
  File "/home/ddan/QtProject/ms.py", line 3, in <module>
    print(c[0].dns.qry.name)
  File "/usr/local/lib/python3.8/dist-packages/pyshark-0.4.3-py3.8.egg/pyshark/packet/layer.py", line 36, in __getattr__
    raise AttributeError()
AttributeError
```
Am I missing something?
Forgive my stupidity.

**Comment by DD152** [comment]
It is my fault.Use `dns.qry_name`.
And in readme.md
> To see all possible field names, use the packet.layer.field_names attribute (i.e. packet.ip.field_names) or the autocomplete function on your interpreter.
So,i should use `packet.dns.field_names` to find out what field names can be used.
