### ISSUE TITLE
Gets error "Error on reading from the event loop self pipe" at exit after parsing pcapng file

### ISSUE THREAD

**Issue by MortenZdk** [KimiNewt/pyshark#487]
The single.pcapng file (attached in .zip) contains a single packet, and is parsed with the script:

```
import pyshark

cap = pyshark.FileCapture('single.pcapng')

print('# WP: Before')
print(cap[0])
print('# WP: After') 

```

This results in the output, with error after the print of packet:

> # WP: Before
> ...
> # WP: After
> Error on reading from the event loop self pipe
> loop: <ProactorEventLoop running=True closed=False debug=False>
> Traceback (most recent call last):
>   File "C:\Python39\lib\asyncio\proactor_events.py", line 777, in _loop_self_reading
>     f = self._proactor.recv(self._ssock, 4096)
>   File "C:\Python39\lib\asyncio\windows_events.py", line 445, in recv
>     self._register_with_iocp(conn)
>   File "C:\Python39\lib\asyncio\windows_events.py", line 718, in _register_with_iocp
>     _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
> OSError: [WinError 87] The parameter is incorrect

So it appears that the error occurs at exit of script, and not during execution.

Versions:
- Python: 3.9.6, 32-bit
- pyshark: 0.4.3

[single.zip](https://github.com/KimiNewt/pyshark/files/6797105/single.zip)

**Comment by ixfd64** [comment]
Try closing the `FileCapture` object with `cap.close()` before the script finishes.

**Comment by heathdbrown** [comment]
I was getting the WinError 87 and the suggested .close() on the capture fixed it, thanks @ixfd64.
