### ISSUE TITLE
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 2). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

### ISSUE THREAD

**Issue by amitsinghkundu** [KimiNewt/pyshark#490]
Facing this tshark crashing issue only on linux , but perfectly working on windows

Exception ignored in: <bound method Capture.__del__ of <FileCapture /home/ubuntu/e2e-taf-robot/suites/Suites.CM-Rm/Registration/2021_08_09/18_46_53_697/WIRESHARK_New_TRAFFIC_2021_08_09_18_47_25.pcap>>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyshark/capture/capture.py", line 430, in __del__
    self.close()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyshark/capture/capture.py", line 420, in close
    self.eventloop.run_until_complete(self._close_async())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/trollius/base_events.py", line 350, in run_until_complete
    return future.result()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/trollius/futures.py", line 287, in result
    raise self._exception
  File "/home/ubuntu/.local/lib/python3.6/site-packages/trollius/tasks.py", line 257, in _step
    result = coro.throw(exc)
  File "<string>", line 11, in pep479_wrapped
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyshark/capture/capture.py", line 425, in _close_async
    yield From(self._cleanup_subprocess(process))
  File "<string>", line 29, in pep479_wrapped
  File "/home/ubuntu/.local/lib/python3.6/site-packages/trollius/tasks.py", line 259, in _step
    result = coro.send(value)
  File "<string>", line 15, in pep479_wrapped
  File "/home/ubuntu/.local/lib/python3.6/site-packages/pyshark/capture/capture.py", line 417, in _cleanup_subprocess
    raise TSharkCrashException('TShark seems to have crashed (retcode: %d). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.' % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 2). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

**Comment by sedrubal** [comment]
I'm not the maintainer of this project, but I think, your issue would help more, when you provide some additional information like how you're creating the Capture and the `tshark` call, that will be used in the background (you can see it, when you enable debugging on the Capture object, like the message hints you) 😉
