### ISSUE TITLE
Some parsing errors when using ek mode

### ISSUE THREAD

**Issue by miaotony** [KimiNewt/pyshark#569]
## bug1
**Describe the bug**

When calling `LiveCapture` and pass parameters `use_ek=True, include_raw=True`, pyshark will throw `TypeError: can only concatenate str (not "int") to str` and then exit.

```
Traceback (most recent call last):
  File "1.py", line 289, in <module>
    cap.apply_on_packets(tshark_callback)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\capture.py", line 245, in apply_on_packets
    return self.eventloop.run_until_complete(coro)
  File "D:\Programs\Anaconda\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\capture.py", line 256, in packets_from_tshark
    await self._go_through_packets_from_fd(tshark_process.stdout, packet_callback, packet_count=packet_count)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\capture\capture.py", line 283, in _go_through_packets_from_fd
    packet_callback(packet)
  File "1.py", line 228, in tshark_callback
    detail_info = get_detail_info(package)
  File "1.py", line 80, in get_detail_info
    print(package)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\packet\packet.py", line 104, in __str__
    s += str(layer)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\packet\layers\base.py", line 69, in __str__
    self.pretty_print(writer=writer)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\packet\layers\base.py", line 59, in pretty_print
    self._pretty_print_layer_fields(writer)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\packet\layers\ek_layer.py", line 83, in _pretty_print_layer_fields
    self._pretty_print_field(field_name, field, terminal_writer, indent=1)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\packet\layers\ek_layer.py", line 94, in _pretty_print_field
    indent=indent + 1)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\packet\layers\ek_layer.py", line 90, in _pretty_print_field
    terminal_writer.write(field.value)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark-0.4.6-py3.7.egg\pyshark\packet\common.py", line 34, in write
    self.buffer += text
TypeError: can only concatenate str (not "int") to str
```

**To Reproduce**

```python
import pyshark

cap = pyshark.LiveCapture(use_ek=True, include_raw=True)
cap.set_debug()
cap.apply_on_packets(tshark_callback)   # tshark_callback is a callback function
```

The bug might be because `field.value` is an integer, so I replace `self.buffer += text` with `self.buffer += str(text)` to fix this problem temporarily. But you'd better use `str()` on `field.value` or something else.

## bug2

When using `use_ek=True, include_raw=True`, some flags in the parsed package will be (nearly) nothing and only/partly have a sub value like `raw: 0`. Seems like the values are not parsed rightly.
Just like follows.

![图片](https://user-images.githubusercontent.com/41962043/178039480-5374d46c-830b-47fd-a19f-16bee6d0e013.png)

However, when I remove the parameter `include_raw=True`, the values will be displayed successfully.

![图片](https://user-images.githubusercontent.com/41962043/178039345-1dfb6fb3-1974-4542-94b0-4223f9d290c6.png)

So some parsing error may happen during the process.

## **Versions:**
- OS: Windows 10
- pyshark version: v0.4.6+ 80faffc7879fc49b2ef9a2aa9a3cd461247a1094 from GitHub
- tshark version: TShark (Wireshark) 3.6.6 (v3.6.6-0-g7d96674e2a30)

**Comment by KimiNewt** [comment]
Fixed. The TerminalWriter would not write anything when `False` was given to it. We cast everything to string now and this fixes both issues.
