### ISSUE TITLE
pyshark 0.5 import failure

### ISSUE THREAD

**Issue by nehaljwani** [KimiNewt/pyshark#570]
```
❯❯❯ python
Python 3.9.7 (default, Aug 30 2021, 00:00:00) 
[GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshark
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/nwani_1657293141/dev/lib64/python3.9/site-packages/pyshark/__init__.py", line 13, in <module>
    from pyshark.capture.live_capture import LiveCapture
ModuleNotFoundError: No module named 'pyshark.capture'
```

**Comment by nehaljwani** [comment]
Also, the source distribution uploaded on PyPi is missing the directory `pyshark/packet/layers/`

**Comment by KimiNewt** [comment]
Yep, there was a problem with the setuptools packaging. Fixed and reuploaded.
