### ISSUE TITLE
`KeyError: 'layers'` when using ek mode and calling `cap.sniff`

### ISSUE THREAD

**Issue by miaotony** [KimiNewt/pyshark#572]
**Describe the bug**
`KeyError: 'layers'` when using ek mode and calling `cap.sniff`.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\Anaconda\lib\site-packages\pyshark\capture\capture.py", line 145, in load_packets
    keep_packet, timeout=timeout, packet_count=packet_count)
    return self.eventloop.run_until_complete(coro)
  File "D:\Programs\Anaconda\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "D:\Programs\Anaconda\lib\asyncio\tasks.py", line 416, in wait_for
    return fut.result()
  File "D:\Programs\Anaconda\lib\site-packages\pyshark\capture\capture.py", line 267, in packets_from_tshark
    await self._go_through_packets_from_fd(tshark_process.stdout, packet_callback, packet_count=packet_count)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark\capture\capture.py", line 285, in _go_through_packets_from_fd
    got_first_packet=packets_captured > 0)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark\tshark\output_parser\base_parser.py", line 15, in get_packets_from_stream
    packet = self._parse_single_packet(packet)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark\tshark\output_parser\tshark_ek.py", line 21, in _parse_single_packet
    return packet_from_ek_packet(packet)
  File "D:\Programs\Anaconda\lib\site-packages\pyshark\tshark\output_parser\tshark_ek.py", line 44, in packet_from_ek_packet
    frame_dict = pkt_dict['layers'].pop('frame')
KeyError: 'layers'
```

**To Reproduce**

Sample code: 

```python
import pyshark

cap = pyshark.LiveCapture(use_ek=True, include_raw=True)
cap.set_debug()
cap.sniff(timeout=3)
```

**Versions**
- OS: Windows 10
- pyshark version: v0.5.2
- tshark version: TShark (Wireshark) 3.6.6 (v3.6.6-0-g7d96674e2a30)

**Comment by miaotony** [comment]
Looks like the first package is parsed successfully, but in the later packages the first byte is `\n` rather than `b'{"ind'`, so after parsing JSON the `pkt_dict` is the `index` dict...

![图片](https://user-images.githubusercontent.com/41962043/178325746-681c079b-1f7e-40c6-8f8a-87055508d7b4.png)
![图片](https://user-images.githubusercontent.com/41962043/178325943-139117e4-85ea-4c1f-8f58-27cc9a6a9334.png)

**Comment by KimiNewt** [comment]
This actually works fine for me on tshark 3.6.5 on linux. I don't think there's any issue with just stripping the `data`, but I'll try and think of a better solution. If you find one, feel free to make a PR.
