### ISSUE TITLE
pyshark error on print (I think this might be my python setup in Cygwin)

### ISSUE THREAD

**Issue by hyperhead** [KimiNewt/pyshark#61]
Hi  I am trying to use pyshark in Cygwin on Windows 7.  I know it works ok, as a colleage of mine has it set up.  However when I try to use pyshark I am getting the following error:

>>> print cap[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.3-py2.7.egg/pyshark/capture/file_capture.py", line 58, in __getitem__
    self.next()
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.3-py2.7.egg/pyshark/capture/file_capture.py", line 48, in next
    packet = self._packet_generator.send(None)
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.3-py2.7.egg/pyshark/capture/capture.py", line 159, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "/usr/lib/python2.7/site-packages/trollius-1.0.4-py2.7.egg/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/lib/python2.7/site-packages/trollius-1.0.4-py2.7.egg/trollius/futures.py", line 287, in result
    raise self._exception
OSError: [Errno 2] No such file or directory

I think maybe my Python installation on cygwin is messed up or the package trollius is.  Has anybody else experienced this before?

**Comment by hyperhead** [comment]
I used python for Windows rather than the Cygwin python, this seems to have solved the issue.
