### ISSUE TITLE
raise RuntimeError('This event loop is already running')

### ISSUE THREAD

**Issue by saifjarboui** [KimiNewt/pyshark#630]
**Describe the bug**
When running filecapture of a bit large pcap file (around 100MB) ;
I get 
Exception ignored in: <function Capture.__del__ at 0x0000021793F5F040>
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\pyshark\capture\capture.py", line 406, in __del__
    self.close()
  File "C:\Python39\lib\site-packages\pyshark\capture\capture.py", line 394, in close
    self.eventloop.run_until_complete(self.close_async())
  File "C:\Python39\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()
  File "C:\Python39\lib\asyncio\base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
C:\Python39\lib\site-packages\pyshark\packet\layers\xml_layer.py:26: RuntimeWarning:

coroutine 'Capture.close_async' was never awaited
 and in other times I get :

Exception ignored in: <function Capture.__del__ at 0x0000021793F5F040>
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\pyshark\capture\capture.py", line 406, in __del__
    self.close()
  File "C:\Python39\lib\site-packages\pyshark\capture\capture.py", line 394, in close
    self.eventloop.run_until_complete(self.close_async())
  File "C:\Python39\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()
  File "C:\Python39\lib\asyncio\base_events.py", line 578, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

**To Reproduce**
Run filecapture in the context that Tshark called many times before closed

**Expected behavior**

**Versions (please complete the following information):**
 - OS: Windows
 - pyshark version: 0.5.3
 - tshark version: 4.0.2

**Comment by Kastalia** [comment]
Solved #366

**Comment by ykalensc** [comment]
I'm still seeing this error on the latest pyshark. 
**Code snippet**
```
 with pyshark.FileCapture(pcap_filepath, display_filter='tls.handshake.type == 2') as capture:
                for packet in capture:
                      <do something>
```
or
```
try:
    capture =  pyshark.FileCapture(pcap_filepath, display_filter='tls.handshake.type == 2')
...
finally:
    capture.close()
```

**Error**
```

 /usr/local/lib/python3.13/site-packages/pyshark/capture/capture.py:183: DeprecationWarning: There is no current event loop
   self.eventloop = asyncio.get_event_loop_policy().get_event_loop()

 it_test/test_tls_fips_validation.py: 18 warnings
 /usr/local/lib/python3.13/site-packages/pyshark/capture/capture.py:200: DeprecationWarning: 'SafeChildWatcher' is deprecated as of Python 3.12 and will be removed in Python 3.14.
   asyncio.set_child_watcher(asyncio.SafeChildWatcher())

 it_test/test_tls_fips_validation.py: 18 warnings
 /usr/local/lib/python3.13/asyncio/events.py:848: DeprecationWarning: 'set_child_watcher' is deprecated as of Python 3.12 and will be removed in Python 3.14.
   return get_event_loop_policy().set_child_watcher(watcher)

 it_test/test_tls_fips_validation.py: 18 warnings
 /usr/local/lib/python3.13/asyncio/events.py:842: DeprecationWarning: 'get_child_watcher' is deprecated as of Python 3.12 and will be removed in Python 3.14.
   return get_event_loop_policy().get_child_watcher()

 it_test/test_tls_fips_validation.py::test_fips_validation
 /usr/local/lib/python3.13/site-packages/_pytest/threadexception.py:77: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1 (status_server_thread)

 Traceback (most recent call last):
   File "/usr/local/lib/python3.13/threading.py", line 1039, in _bootstrap_inner
     self.run()
     ~~~~~~~~^^
   File "/usr/local/lib/python3.13/threading.py", line 990, in run
     self._target(*self._args, **self._kwargs)
     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 TypeError: status_server_thread() takes 1 positional argument but 11 were given

   warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```
**Versions**
- OS: Ubuntu
- pyshark version: 0.6
- tshark version: 4.0.11
- python version: 3.9 and 3.13

**Comment by amlamarra** [comment]
@saifjarboui Can you provide example code that leads to this problem? And, preferably, where to find a sample pcap file that causes it.

Does the resolution in #336 fix this for you?
