### ISSUE TITLE
data._all_fields is not working with use_ek

### ISSUE THREAD

**Issue by strukevych** [KimiNewt/pyshark#667]
**Describe the bug**
startswith is called on dict

```
Traceback (most recent call last):
  File "C:\Users\Yaroslav\Documents\data_bot\parser-cap.py", line 116, in <module>
    if ("tls.reassembled.data" in x.data._all_fields):
  File "C:\Python310\lib\site-packages\pyshark\packet\layers\base.py", line 46, in __getattr__
    val = self.get_field(item)
  File "C:\Python310\lib\site-packages\pyshark\packet\layers\ek_layer.py", line 54, in get_field
    nested_field = self._get_nested_field(prefix, name)
  File "C:\Python310\lib\site-packages\pyshark\packet\layers\ek_layer.py", line 98, in _get_nested_field
    if possible_nested_name.startswith(f"{field_ek_name}_"):
AttributeError: 'dict' object has no attribute 'startswith'
```

**To Reproduce**
```
cap = pyshark.FileCapture('data.pcapng', display_filter="websocket and ip.src != 192.168.0.0/16", include_raw=True, use_ek=True)

for x in cap:
  if 'DATA' in x:
    if "tls.reassembled.data" in x.data._all_fields:
      pass
```

**Expected behavior**
Same behavior as with XML packet version

**Versions (please complete the following information):**
 - OS: Windows
 - pyshark version: 0.6
 - tshark version: 4.0.6

**Comment by kholzapfel** [comment]
Experiencing the same issue. It occurs when a layer appears multiple times in a packet. In this situation, self._fields_dict becomes a list of dictionaries rather than the expected single dictionary.
