### ISSUE TITLE
Pyshark only work good with Linux??

### ISSUE THREAD

**Issue by malli02422** [KimiNewt/pyshark#68]
Hi All,
I am not able to use this pyshark Library with windows environment .
import pyshark

cap = pyshark.FileCapture('D:\mallik.pcap')
print cap.**len**()
for i in cap:
    print i

The Result is as follows.
C:\Python27\python.exe "D:/Trailproject/add two number.py" 2 3 4
0
Traceback (most recent call last):
  File "D:/Trailproject/add two number.py", line 5, in <module>
    for i in cap:
  File "C:\Python27\lib\site-packages\pyshark\capture\capture.py", line 159, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 300, in run_until_complete
    return future.result()
  File "C:\Python27\lib\site-packages\trollius\futures.py", line 287, in result
    raise self._exception
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

Process finished with exit code 1

Please some one help me to get the information whether it can able useful in windows., if so let me know it with example.
I can see other issues far beyond the basic it means it is working for them .
I am use Windows 7 as my OS.

**Comment by KimiNewt** [comment]
Pyshark works properly on Windows. 
The problem is with the path to your cap file. Try using r'D:\mallik.pcap' instead.
If you can't run open(r'D:\mallik.pcap'), it has nothing to do with pyshark.

**Comment by malli02422** [comment]
import pyshark

cap = pyshark.FileCapture(r'D:\mallik.pcap')
print cap.__len__()
for i in cap:
    print i


C:\Python27\python.exe D:/Trailproject/packetCapture.py
0
Traceback (most recent call last):
  File "D:/Trailproject/packetCapture.py", line 5, in <module>
    for i in cap:
  File "C:\Python27\lib\site-packages\pyshark\capture\capture.py", line 159, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 300, in run_until_complete
    return future.result()
  File "C:\Python27\lib\site-packages\trollius\futures.py", line 287, in result
    raise self._exception
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

Process finished with exit code 1

**Comment by malli02422** [comment]
Still not working , please some one help to just get start with it

**Comment by KimiNewt** [comment]
Please run `pyshark.tshark.tshark.get_tshark_path()` and see if tshark is in that location.

**Comment by malli02422** [comment]
import pyshark

cap = pyshark.FileCapture(r'D:\\mallik.pcap')
new= pyshark.tshark.tshark.get_tshark_path()
print new


An d the output  I got is 
C:\Python27\python.exe D:/Trailproject/packetCapture.py
C:\Program Files\Wireshark\tshark.exe

Process finished with exit code 0

**Comment by malli02422** [comment]
Thanks for the reply now please let me know what to do

**Comment by malli02422** [comment]
Hello any one help me resolving the issue .. Thanks in advance

**Comment by malli02422** [comment]
I have tried all the alternatives ...  need some help to get ride of this problem

**Comment by KimiNewt** [comment]
Please attempt to run
f = open(r"C:\Program Files\Wireshark\tshark.exe", "rb")
f.read(1)
f.close()

Does that work? If so, try running the tshark.exe and make sure that it
works properly.
Pyshark works in Windows. The problem is on your end when attempting to run
tshark.

**Comment by malli02422** [comment]
Thanks for the replay ,
I have executed the above code and it is executed successfully , even I have verified the TShark command manually  which also working fine . Please check the attached output .
import pyshark
f = open(r"C:\Program Files\Wireshark\tshark.exe", "rb")
f.read(1)
f.close()

C:\Python27\python.exe D:/Trailproject/packetCapture.py

Process finished with exit code 0


I  have written another program which print the interfaces which also working fine .
import subprocess
p = subprocess.Popen([r"C:\Program Files\Wireshark\tshark.exe","-D"],stdout=subprocess.PIPE)
out,err = p.communicate()
print out
C:\Python27\python.exe D:/Trailproject/packcapture.py
1. \Device\NPF_{C4B0E11F-0348-4F56-AE12-4CB6C2AF9CCD} (Local Area Connection)
2. \Device\NPF_{40AF8ABD-545C-4DA7-9D55-5239865526A3} (VirtualBox Host-Only Network)
3. \Device\NPF_{B6981862-F94D-40C1-B846-9F79CFFAC6FB} (Wireless Network Connection)


Process finished with exit code 0


Please let me know if I missed out any thing

**Comment by KimiNewt** [comment]
Try specifying the tshark path with the new tshark_path argument of the FileCapture object. Does that work?

**Comment by malli02422** [comment]
Hi ,
It is same old story 
import pyshark


cap = pyshark.FileCapture(input_file= r'C:\mallik.cap',tshark_path='C:\Program Files\Wireshark\tshark.exe')

print cap[0]


C:\Python27\python.exe C:/pyexample/test.py
Traceback (most recent call last):
  File "C:/pyexample/test.py", line 6, in <module>
    print cap[0]
  File "C:\Python27\lib\site-packages\pyshark\capture\file_capture.py", line 63, in __getitem__
    self.next()
  File "C:\Python27\lib\site-packages\pyshark\capture\file_capture.py", line 53, in next
    packet = self._packet_generator.send(None)
  File "C:\Python27\lib\site-packages\pyshark\capture\capture.py", line 162, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 300, in run_until_complete
    return future.result()
  File "C:\Python27\lib\site-packages\trollius\futures.py", line 287, in result
    raise self._exception
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

Process finished with exit code 1

**Comment by KimiNewt** [comment]
Use "r" in front of the tshark string, too.

**Comment by malli02422** [comment]
import pyshark

cap = pyshark.FileCapture(input_file= r'C:\mallik.cap',tshark_path=r'C:\Program Files\Wireshark\tshark.exe')

print cap[0]


C:\Python27\python.exe C:/pyexample/test.py
Traceback (most recent call last):
  File "C:/pyexample/test.py", line 5, in <module>
    print cap[0]
  File "C:\Python27\lib\site-packages\pyshark\capture\file_capture.py", line 63, in __getitem__
    self.next()
  File "C:\Python27\lib\site-packages\pyshark\capture\file_capture.py", line 53, in next
    packet = self._packet_generator.send(None)
  File "C:\Python27\lib\site-packages\pyshark\capture\capture.py", line 162, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 300, in run_until_complete
    return future.result()
  File "C:\Python27\lib\site-packages\trollius\futures.py", line 287, in result
    raise self._exception
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect

Process finished with exit code 1

**Comment by AkuPython** [comment]
Try moving the PCAP to a different folder and ensure the file permissions are correctly set. It could be that your user (Admin) can open it in Wireshark but Python (User) doesn't even have read access set.

I had a couple of issues, I ran the commands in the interactive shell and worked out my error accessing my file, so that might help you too.

**Comment by bdeweese** [comment]
Two questions:  

1. Was the issue in the above thread ever resolved?
2. Is there any known issues with support for this pyshark under Win7 + cygwin (32-bit)? 

I have a very basic pcap file that I can ready with tshark using the cygwin directory structure format.

#bdeweese 02/25/16 19:04:27 {foo}/cygdrive/c/Program\ Files/Wireshark/tshark.exe  -r capture.pcap
  1   0.000000      8.8.8.8 -> 192.168.1.13 ICMP Echo (ping) reply    id=0x0001, seq=1055/7940, ttl=55
  2   1.003170      8.8.8.8 -> 192.168.1.13 ICMP Echo (ping) reply    id=0x0001, seq=1056/8196, ttl=55
  3   2.003198      8.8.8.8 -> 192.168.1.13 ICMP Echo (ping) reply    id=0x0001, seq=1057/8452, ttl=55
  4   3.003217      8.8.8.8 -> 192.168.1.13 ICMP Echo (ping) reply    id=0x0001, seq=1058/8708, ttl=55
bdeweese 02/25/16 19:04:48 {foo}

With the default of 2.7.10, it reports a similar error as in the thread above. 

bdeweese 02/25/16 19:06:26 {foo}python
Python 2.7.10 (default, Jun  1 2015, 18:17:45)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshark
**No handlers could be found for logger "trollius"**
>>> cap = pyshark.FileCapture(input_file= r'/cygdrive/c/foo/capture.pcap',tshark_path=r'/cygdrive/c/Program\ Files/Wireshark/tshark.exe')
>>> print cap[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.6.1-py2.7.egg/pyshark/capture/file_capture.py", line 65, in __getitem__
    self.next()
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.6.1-py2.7.egg/pyshark/capture/file_capture.py", line 55, in next
    packet = self._packet_generator.send(None)
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.6.1-py2.7.egg/pyshark/capture/capture.py", line 165, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "/usr/lib/python2.7/site-packages/trollius-1.0.4-py2.7.egg/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/lib/python2.7/site-packages/trollius-1.0.4-py2.7.egg/trollius/futures.py", line 287, in result
    raise self._exception
OSError: [Errno 2] No such file or directory
>>>




If I run it in Python 3.4 its the same sort of thing, although more descriptive and the additional information seems to indicate it is having issues locating the tshark.exe. 


bdeweese 02/25/16 19:16:06 {foo}alias p3='/usr/bin/python3.4m.exe'
bdeweese 02/25/16 19:16:08 {foo}p3
Python 3.4.3 (default, May  5 2015, 17:04:32)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshark
time_monotonic: unspported platform 'cygwin'
>>> cap = pyshark.FileCapture(input_file= r'/cygdrive/c/foo/capture.pcap',tshark_path=r'/cygdrive/c/Program\ Files/Wireshark/tshark.exe')
>>> print (cap[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/pyshark-0.3.6.1-py3.4.egg/pyshark/capture/file_capture.py", line 63, in __getitem__
    next(self)
  File "/usr/lib/python3.4/site-packages/pyshark-0.3.6.1-py3.4.egg/pyshark/capture/file_capture.py", line 53, in __next__
    packet = self._packet_generator.send(None)
  File "/usr/lib/python3.4/site-packages/pyshark-0.3.6.1-py3.4.egg/pyshark/capture/capture.py", line 164, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/futures.py", line 287, in result
    raise self._exception
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.4/site-packages/pyshark-0.3.6.1-py3.4.egg/pyshark/capture/capture.py", line 307, in _get_tshark_process
    stdin=stdin))
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/subprocess.py", line 245, in create_subprocess_exec
    stderr=stderr, **kwds))
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/tasks.py", line 251, in _step
    result = coro.throw(exc)
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/base_events.py", line 899, in subprocess_exec
    bufsize, **kwargs))
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/tasks.py", line 255, in _step
    result = next(coro)
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/unix_events.py", line 206, in _make_subprocess_transport
    extra=extra, **kwargs)
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/base_subprocess.py", line 31, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.4/site-packages/trollius-1.0.4-py3.4.egg/trollius/unix_events.py", line 612, in _start
    universal_newlines=False, bufsize=bufsize, **kwargs)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Wireshark\\tshark.exe'
>>>


Any info on how this could perhaps work with cygwin would be appreciated.

**Comment by bdeweese** [comment]
Hmmm...  Moving right along.

There is the config.ini file with this package.

I re-installed my base Wireshark into a simpler  c:\Wireshark area to simplify the path and added that to the config.ini ... 

[tshark]
# Specify the path to the tshark executable.
# If the configured path does not exist, these locations will be searched:
# (Linux): /usr/bin/tshark
# (Linux): /usr/sbin/tshark
# (Linux): /usr/lib/tshark/tshark
# (Linux): /usr/local/bin/tshark
# (Windows): %ProgramFiles%\Wireshark\tshark.exe
# (Windows): %ProgramFiles(x86)%\Wireshark\tshark.exe
# tshark_path = C:\Program Files\Wireshark\tshark.exe
**tshark_path = /cygdrive/c/Wireshark/tshark.exe**

 and re-ran the following:

easy_install-2.7 ./KimiNewt-pyshark-8b55bdf/

Now I am on the same page with Wireshark for Cygwin.    Something similar may help in the above case since the user is using D:\.

>>> pyshark.tshark.tshark.get_tshark_path()
'/cygdrive/c/Wireshark/tshark.exe'
>>>

>>> pyshark.tshark.tshark.get_tshark_version()
u'2.0.1'

>>> pyshark.tshark.tshark.get_tshark_interfaces()
[u'1', u'2', u'3', u'4']
>>>

So I am happier than before, but there still seems to be something in the way this works with Wireshark package 2.0.1 or some other issue.   The tshark is accused of crashing with errno 2. 


Exception pyshark.capture.capture.TSharkCrashException: TSharkCrashException(u'TShark seems to have crashed (retcode: 2). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.',) in <bound method FileCapture.__del__ of <FileCapture /cygdrive/c/foo/capture.pcap>> ignored




bdeweese 02/25/16 21:49:34 {foo}python
Python 2.7.10 (default, Jun  1 2015, 18:17:45)
[GCC 4.9.2] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyshark
No handlers could be found for logger "trollius"
>>> cap = pyshark.FileCapture(input_file=r'/cygdrive/c/foo/capture.pcap',tshark_path=r'/cygdrive/Wireshark/tshark.exe')
>>>
>>> print cap[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.6.1-py2.7.egg/pyshark/capture/file_capture.py", line 65, in __getitem__
    self.next()
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.6.1-py2.7.egg/pyshark/capture/file_capture.py", line 55, in next
    packet = self._packet_generator.send(None)
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.6.1-py2.7.egg/pyshark/capture/capture.py", line 184, in _packets_from_tshark_sync
    self._cleanup_subprocess(tshark_process)
  File "/usr/lib/python2.7/site-packages/pyshark-0.3.6.1-py2.7.egg/pyshark/capture/capture.py", line 323, in _cleanup_subprocess
    process.kill()
  File "/usr/lib/python2.7/site-packages/trollius-1.0.4-py2.7.egg/trollius/subprocess.py", line 150, in kill
    self._transport.kill()
  File "/usr/lib/python2.7/site-packages/trollius-1.0.4-py2.7.egg/trollius/base_subprocess.py", line 97, in kill
    self._proc.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1564, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1554, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 13] Permission denied
>>>
Exception OSError: OSError(3, 'No such process') in <bound method FileCapture.__del__ of <FileCapture /cygdrive/c/foo/capture.pcap>> ignored
Aborted (core dumped)
bdeweese 02/25/16 22:04:24 {foo}

**Comment by manishkk** [comment]
I am using PyCharm IDE for Python, 

I tried to install pyshark package  but not able to install.
I am using Ubuntu, Please give some suggestion.

Thanks

**Comment by ayedaemon** [comment]
> 
> 
> import pyshark
> 
> cap = pyshark.FileCapture(r'D:\mallik.pcap')
> new= pyshark.tshark.tshark.get_tshark_path()
> print new
> 
> An d the output I got is
> C:\Python27\python.exe D:/Trailproject/packetCapture.py
> C:\Program Files\Wireshark\tshark.exe
> 
> Process finished with exit code 0

i am getting error in this!
i have installed wireshark for windows;
Also have set its path into system variables.
