### ISSUE TITLE
Please support Python2.6 or throw a user-friendly error

### ISSUE THREAD

**Issue by mpenning** [KimiNewt/pyshark#83]
``pyshark`` seems to require Python2.7 features.

This is the traceback I get when I try importing ``pyshark`` under Python 2.6.

    (py26_pyshark)[mpenning@tsunami ~]$ python
    Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
    [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pyshark import FileCapture
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/virtual_env/py26_pyshark/lib/python2.6/site-packages/pyshark/__init__.py", line 1, in <module>
        from pyshark.capture.live_capture import LiveCapture
      File "/opt/virtual_env/py26_pyshark/lib/python2.6/site-packages/pyshark/capture/live_capture.py", line 1, in <module>
        from pyshark.capture.capture import Capture
      File "/opt/virtual_env/py26_pyshark/lib/python2.6/site-packages/pyshark/capture/capture.py", line 12, in <module>
        from pyshark.tshark.tshark_xml import packet_from_xml_packet, psml_structure_from_xml
      File "/opt/virtual_env/py26_pyshark/lib/python2.6/site-packages/pyshark/tshark/tshark_xml.py", line 5, in <module>
        from pyshark.packet.layer import Layer
      File "/opt/virtual_env/py26_pyshark/lib/python2.6/site-packages/pyshark/packet/layer.py", line 57
        return {slot: getattr(self, slot) for slot in self.__slots__}
                                            ^
    SyntaxError: invalid syntax
    >>> quit()
    (py26_pyshark)[mpenning@tsunami ~]$

This fails because Py2.6 doesn't support a dictionary comprehension.  However, a lot of enterprise users run Redhat / CentOS versions which still ship with Python 2.6

Please either:

1. Support and unit-test against Python2.6 (hint: [Travis CI](https://travis-ci.org/ "Travis CI") is very useful for testing against multiple python versions, I do this myself when I build [ciscoconfparse](https://github.com/mpenning/ciscoconfparse))
2. Test for Python 2.7 and throw a user-friendly error if Python 2.7 isn't available

**Comment by KimiNewt** [comment]
Support restored and added 2.6 to the travis configuration.
