### ISSUE TITLE
pyshark issue while trying to parser wireshark.pcap file

### ISSUE THREAD

**Issue by usharadhya** [KimiNewt/pyshark#91]
After importing pyshark in python file if i use 
cap = pyshark.FileCapture(r'/home/new/new_001.pcap')
print cap[0]
i'm unable find the packet information been printed. Following error is seen 

Traceback (most recent call last):
  File "test.py", line 42, in <module>
    print cap[0]
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/file_capture.py", line 63, in **getitem**
    self.next()
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/file_capture.py", line 53, in next
    packet = self._packet_generator.send(None)
  File "/usr/local/lib/python2.7/dist-packages/pyshark/capture/capture.py", line 162, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "/usr/local/lib/python2.7/dist-packages/trollius/base_events.py", line 300, in run_until_complete
    return future.result()
  File "/usr/local/lib/python2.7/dist-packages/trollius/futures.py", line 287, in result
    raise self._exception
OSError: [Errno 13] Permission denied

**Comment by kkxue** [comment]
how about using root username to run python?

**Comment by gagomes** [comment]
@usharadhya as @kkxue said, you will need to run your script/python as privileged user (or configure your session to have CAP_NET_ADMIN|CAP_NET_RAW capabilities)
